// <auto-generated />
using System;
using AplicadaBlazorParcial2.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AplicadaBlazorParcial2.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.Clientes", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .HasColumnType("TEXT");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Nombres = "FERRETERIA GAMA"
                        },
                        new
                        {
                            ClienteId = 2,
                            Nombres = "AVALON DISCO"
                        },
                        new
                        {
                            ClienteId = 3,
                            Nombres = "PRESTAMOS CEFIPROD"
                        });
                });

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.Cobros", b =>
                {
                    b.Property<int>("CobroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cobro")
                        .HasColumnType("REAL");

                    b.Property<int>("ConteoCobro")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalesCobro")
                        .HasColumnType("REAL");

                    b.HasKey("CobroId");

                    b.ToTable("Cobros");
                });

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.CobrosDetalles", b =>
                {
                    b.Property<int>("CobroDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Cobrado")
                        .HasColumnType("REAL");

                    b.Property<int>("CobroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CobroDetalleId");

                    b.HasIndex("CobroId");

                    b.HasIndex("VentaId");

                    b.ToTable("CobrosDetalles");
                });

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.Ventas", b =>
                {
                    b.Property<int>("VentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Balance")
                        .HasColumnType("REAL");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cobrado")
                        .HasColumnType("REAL");

                    b.Property<bool>("CobroNoPerdiente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("Monto")
                        .HasColumnType("REAL");

                    b.HasKey("VentaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ventas");

                    b.HasData(
                        new
                        {
                            VentaId = 1,
                            Balance = 1000f,
                            ClienteId = 1,
                            Cobrado = 0.0,
                            CobroNoPerdiente = false,
                            Fecha = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 1000f
                        },
                        new
                        {
                            VentaId = 2,
                            Balance = 800f,
                            ClienteId = 1,
                            Cobrado = 0.0,
                            CobroNoPerdiente = false,
                            Fecha = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 900f
                        },
                        new
                        {
                            VentaId = 3,
                            Balance = 2000f,
                            ClienteId = 2,
                            Cobrado = 0.0,
                            CobroNoPerdiente = false,
                            Fecha = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 2000f
                        },
                        new
                        {
                            VentaId = 4,
                            Balance = 1800f,
                            ClienteId = 2,
                            Cobrado = 0.0,
                            CobroNoPerdiente = false,
                            Fecha = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 1900f
                        },
                        new
                        {
                            VentaId = 5,
                            Balance = 3000f,
                            ClienteId = 3,
                            Cobrado = 0.0,
                            CobroNoPerdiente = false,
                            Fecha = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 3000f
                        },
                        new
                        {
                            VentaId = 6,
                            Balance = 1900f,
                            ClienteId = 3,
                            Cobrado = 0.0,
                            CobroNoPerdiente = false,
                            Fecha = new DateTime(2020, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 2900f
                        });
                });

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.CobrosDetalles", b =>
                {
                    b.HasOne("AplicadaBlazorParcial2.Models.Cobros", "Cobro")
                        .WithMany("cobrosDetalles")
                        .HasForeignKey("CobroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AplicadaBlazorParcial2.Models.Ventas", "Venta")
                        .WithMany("cobrosDetalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobro");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.Ventas", b =>
                {
                    b.HasOne("AplicadaBlazorParcial2.Models.Clientes", "Clientes")
                        .WithMany("Ventas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.Clientes", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.Cobros", b =>
                {
                    b.Navigation("cobrosDetalles");
                });

            modelBuilder.Entity("AplicadaBlazorParcial2.Models.Ventas", b =>
                {
                    b.Navigation("cobrosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
